### ISSUE TITLE
Support for multiple annotations on single widget

### ISSUE THREAD

**Issue by luca-vz** [ikbendewilliam/get_x_navigation_generator#3]
Have the possibility to have multiple navigation types e.g.: one to replace everything before the screen and one that pushes it as a new screen with the possibility to go back

**Comment by ikbendewilliam** [comment]
Make `NavigationType` a list with a method for each value or add a way to override the navigationType in the generated method 🤔

**Comment by ikbendewilliam** [comment]
Support for multiple annotations will solve this
