### ISSUE TITLE
Support to specify a navigatorKey

### ISSUE THREAD

**Issue by luca-vz** [ikbendewilliam/get_x_navigation_generator#8]

**Comment by ikbendewilliam** [comment]
https://github.com/jonataslaw/getx/issues/552#issuecomment-686158966
>No widget (yet) to deal with nested navigators, the "key" (pun intended) is to use Navigator( key: Get.nestedKey(int) ... and any GetX navigation command using the same id (int) that you use to create the nestedKey.

See comment for demo

This means that we require support to specify a navigatorKey

**Comment by ikbendewilliam** [comment]
I've added a `navigatorId` to the methods. 
You can specify a nested Navigator like this:
```dart
Navigator(
  key: Get.nestedKey(widget.id),
  onGenerateRoute: (settings) {
    final page = MainNavigator.pages.firstWhere((element) => element.name == settings.name);
    return GetPageRoute<dynamic>(
      page: page.page,
      settings: settings,
      binding: page.binding,
      transition: page.transition,
      opaque: page.opaque,
      popGesture: page.popGesture,
      fullscreenDialog: page.fullscreenDialog,
      maintainState: page.maintainState,
      curve: page.curve,
      middlewares: page.middlewares,
    );
  },
);
```
![image](https://user-images.githubusercontent.com/20164321/221667627-5fed0523-4b20-4356-a5d1-78d9a64cb5a2.png)
